import fs from 'fs'
import path from 'path'
import type { BrowserWindow } from 'electron'
import type { ServerCreateRequest, ServerInfo } from '../shared/ipc-types'

const META_FILE = 'msm.json'

export function listServers(serversFolder: string): ServerInfo[] {
  if (!fs.existsSync(serversFolder)) return []
  return fs
    .readdirSync(serversFolder, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .flatMap((dir) => {
      try {
        return [JSON.parse(fs.readFileSync(path.join(serversFolder, dir.name, META_FILE), 'utf-8')) as ServerInfo]
      } catch { return [] }
    })
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export function getServer(serversFolder: string, name: string): ServerInfo | null {
  return listServers(serversFolder).find((s) => s.name === name) ?? null
}

export function deleteServer(serversFolder: string, name: string): void {
  const serverPath = path.join(serversFolder, name)
  if (!fs.existsSync(serverPath)) throw new Error(`Server "${name}" not found.`)
  fs.rmSync(serverPath, { recursive: true, force: true })
}

export async function createServer(
  serversFolder: string,
  req: ServerCreateRequest,
  win: BrowserWindow | null
): Promise<ServerInfo> {
  const serverPath = path.join(serversFolder, req.name)
  if (fs.existsSync(serverPath)) throw new Error(`A server named "${req.name}" already exists.`)

  fs.mkdirSync(serverPath, { recursive: true })

  const jarPath = path.join(serverPath, req.build.download.name)
  await downloadWithProgress(req.build.download.url, jarPath, req.build.download.size, (pct) => {
    win?.webContents.send('server:download-progress', { name: req.name, percent: pct })
  })

  fs.writeFileSync(
    path.join(serverPath, 'eula.txt'),
    `#Generated by Minecraft Server Manager\neula=${req.acceptEula ? 'true' : 'false'}\n`
  )

  fs.writeFileSync(
    path.join(serverPath, 'server.properties'),
    [
      '#Generated by Minecraft Server Manager',
      `server-name=${req.name}`,
      `server-port=${req.port}`,
      'online-mode=true',
      'difficulty=normal',
      'gamemode=survival',
      'max-players=20',
      'enable-rcon=true',
      `rcon.port=${req.rconPort}`,
      `rcon.password=${req.rconPassword}`,
      ''
    ].join('\n')
  )

  const info: ServerInfo = {
    name:         req.name,
    path:         serverPath,
    version:      req.version,
    build:        req.build.number,
    createdAt:    new Date().toISOString(),
    port:         req.port,
    rconPort:     req.rconPort,
    rconPassword: req.rconPassword,
    ram:          req.ram,
    jarName:      req.build.download.name,
    javaFlags:    req.build.javaFlags
  }
  fs.writeFileSync(path.join(serverPath, META_FILE), JSON.stringify(info, null, 2))

  return info
}

async function downloadWithProgress(
  url: string, dest: string, totalSize: number,
  onProgress: (pct: number) => void
): Promise<void> {
  const response = await fetch(url, { redirect: 'follow' })
  if (!response.ok) throw new Error(`Download failed: HTTP ${response.status}`)

  const reader = response.body!.getReader()
  const file   = fs.createWriteStream(dest)
  let downloaded = 0

  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      file.write(value)
      downloaded += value.length
      if (totalSize > 0) onProgress(Math.round((downloaded / totalSize) * 100))
    }
  } finally {
    file.end()
    await new Promise<void>((res, rej) => { file.on('finish', res); file.on('error', rej) })
  }
}
